# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  schedule:
    - cron: "0 2 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: bash bin/build.sh

      - name: Run a multi-line script
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: build
          
