# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  schedule:
    - cron: "0 0 1 * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: bash contrib/build.sh

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: build
          
